CREATE TABLE analysts
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(254) NOT NULL,
  user_id BIGINT NOT NULL REFERENCES users(id)
);

ALTER TABLE analysts ADD CONSTRAINT analysts_email_user_id_uk UNIQUE (email, user_id);
